Repository Xiangyu-Hu/SPHinXsys, pull requests merged in 2025-02, with the labels that each got.

#738 Xiangyu/body part by cell
  src/for_2D_build/meshes/cell_linked_list_2d.cpp
  src/for_3D_build/meshes/cell_linked_list_3d.cpp
  src/shared/bodies/base_body.h
  src/shared/bodies/base_body_part.cpp
  src/shared/bodies/base_body_part.h
  src/shared/body_relations/base_body_relation.h
  src/shared/body_relations/contact_body_relation.cpp
  src/shared/body_relations/contact_body_relation.h
  src/shared/body_relations/inner_body_relation.cpp
  src/shared/body_relations/inner_body_relation.h
  src/shared/common/base_data_type.h
  src/shared/common/sphinxsys_variable.h
  src/shared/meshes/base_mesh.h
  src/shared/meshes/cell_linked_list.cpp
  src/shared/meshes/cell_linked_list.h
  src/shared/meshes/cell_linked_list.hpp
  src/shared/particle_dynamics/base_local_dynamics.h
  src/shared/particle_dynamics/reduce_functors.h
  src/shared/shared_ck/particle_dynamics/configuration_dynamics/particle_sort_ck.hpp
  src/shared/shared_ck/particle_dynamics/configuration_dynamics/update_cell_linked_list.hpp
  src/shared/shared_ck/particle_dynamics/general_dynamics/general_reduce_ck.h
  src/shared/shared_ck/particle_dynamics/general_dynamics/general_reduce_ck.hpp
  src/shared/shared_ck/particle_dynamics/loop_range.h
  src/shared/shared_ck/particle_dynamics/particle_iterators_ck.h
  src/shared/shared_ck/particle_dynamics/simple_algorithms_ck.h
  src/src_sycl/shared/particle_dynamics/particle_iterators_sycl.h
  tests/2d_examples/2d_examples_ck/test_2d_stfb_ck/stfb.cpp
  tests/2d_examples/2d_examples_ck/test_2d_still_water_ck/CMakeLists.txt
  tests/2d_examples/2d_examples_ck/test_2d_still_water_ck/regression_test_tool/FreeSurfaceGauge_FreeSurfaceHeight_Run_0_result.xml
  tests/2d_examples/2d_examples_ck/test_2d_still_water_ck/regression_test_tool/FreeSurfaceGauge_FreeSurfaceHeight_Run_5_result.xml
  tests/2d_examples/2d_examples_ck/test_2d_still_water_ck/regression_test_tool/FreeSurfaceGauge_FreeSurfaceHeight_dtwdistance.xml
  tests/2d_examples/2d_examples_ck/test_2d_still_water_ck/regression_test_tool/FreeSurfaceGauge_FreeSurfaceHeight_runtimes.dat
  tests/2d_examples/2d_examples_ck/test_2d_still_water_ck/regression_test_tool/regression_test_tool.py
  tests/2d_examples/2d_examples_ck/test_2d_still_water_ck/stlw.cpp
  tests/tests_sycl/2d_examples/test_2d_stfb_sycl/stfb.cpp
  tests/tests_sycl/2d_examples/test_2d_still_water_sycl/CMakeLists.txt
  tests/tests_sycl/2d_examples/test_2d_still_water_sycl/regression_test_tool/FreeSurfaceGauge_FreeSurfaceHeight_Run_0_result.xml
  tests/tests_sycl/2d_examples/test_2d_still_water_sycl/regression_test_tool/FreeSurfaceGauge_FreeSurfaceHeight_Run_5_result.xml
  tests/tests_sycl/2d_examples/test_2d_still_water_sycl/regression_test_tool/FreeSurfaceGauge_FreeSurfaceHeight_dtwdistance.xml
  tests/tests_sycl/2d_examples/test_2d_still_water_sycl/regression_test_tool/FreeSurfaceGauge_FreeSurfaceHeight_runtimes.dat
  tests/tests_sycl/2d_examples/test_2d_still_water_sycl/regression_test_tool/regression_test_tool.py
  tests/tests_sycl/2d_examples/test_2d_still_water_sycl/stlw_sycl.cpp
Labels: sycl_ck

#750 draft the contact diffusion
  .github/workflows/ci.yml
  src/shared/bodies/base_body.h
  src/shared/common/sphinxsys_containers.h
  src/shared/particle_dynamics/diffusion_reaction_dynamics/diffusion_dynamics.cpp
  src/shared/particle_dynamics/diffusion_reaction_dynamics/diffusion_dynamics.h
  src/shared/particles/base_particles.cpp
  src/shared/particles/base_particles.h
  src/shared/particles/base_particles.hpp
  src/shared/physical_closure/materials/diffusion_reaction.h
  src/shared/shared_ck/particle_dynamics/complex_algorithms_ck.h
  src/shared/shared_ck/particle_dynamics/diffusion_reaction_dynamics/diffusion_dynamics_ck.h
  src/shared/shared_ck/particle_dynamics/diffusion_reaction_dynamics/diffusion_dynamics_ck.hpp
  src/shared/shared_ck/particle_dynamics/general_dynamics/general_initial_condition.h
  src/shared/shared_ck/particle_dynamics/interaction_ck.h
  tests/2d_examples/2d_examples_ck/test_0d_regression_test_ck/regression_test.cpp
  tests/2d_examples/2d_examples_ck/test_2d_diffusion_NeumannBC_ck/CMakeLists.txt
  tests/2d_examples/2d_examples_ck/test_2d_diffusion_NeumannBC_ck/diffusion_NeumannBC.cpp
  tests/2d_examples/2d_examples_ck/test_2d_diffusion_NeumannBC_ck/regression_test_tool/TemperatureObserver_Phi_ensemble_averaged_mean_variance.xml
  tests/2d_examples/2d_examples_ck/test_2d_diffusion_NeumannBC_ck/regression_test_tool/TemperatureObserver_Phi_result.xml
  tests/2d_examples/2d_examples_ck/test_2d_diffusion_NeumannBC_ck/regression_test_tool/TemperatureObserver_Phi_runtimes.dat
  tests/2d_examples/2d_examples_ck/test_2d_diffusion_NeumannBC_ck/regression_test_tool/regression_test_tool.py
  tests/2d_examples/2d_examples_ck/test_2d_stfb_ck/stfb.cpp
  tests/2d_examples/2d_examples_ck/test_2d_water_entry_exit_ck/CMakeLists.txt
  tests/2d_examples/2d_examples_ck/test_2d_water_entry_exit_ck/regression_test_tool/CylinderObserver_Position_Run_0_result.xml
  tests/2d_examples/2d_examples_ck/test_2d_water_entry_exit_ck/regression_test_tool/CylinderObserver_Position_Run_15_result.xml
  tests/2d_examples/2d_examples_ck/test_2d_water_entry_exit_ck/regression_test_tool/CylinderObserver_Position_Run_7_result.xml
  tests/2d_examples/2d_examples_ck/test_2d_water_entry_exit_ck/regression_test_tool/CylinderObserver_Position_dtwdistance.xml
  tests/2d_examples/2d_examples_ck/test_2d_water_entry_exit_ck/regression_test_tool/CylinderObserver_Position_runtimes.dat
  tests/2d_examples/2d_examples_ck/test_2d_water_entry_exit_ck/regression_test_tool/WettingObserver_Phi_Run_0_result.xml
  tests/2d_examples/2d_examples_ck/test_2d_water_entry_exit_ck/regression_test_tool/WettingObserver_Phi_Run_11_result.xml
  tests/2d_examples/2d_examples_ck/test_2d_water_entry_exit_ck/regression_test_tool/WettingObserver_Phi_Run_5_result.xml
  tests/2d_examples/2d_examples_ck/test_2d_water_entry_exit_ck/regression_test_tool/WettingObserver_Phi_dtwdistance.xml
  tests/2d_examples/2d_examples_ck/test_2d_water_entry_exit_ck/regression_test_tool/WettingObserver_Phi_runtimes.dat
  tests/2d_examples/2d_examples_ck/test_2d_water_entry_exit_ck/regression_test_tool/regression_test_tool.py
  tests/2d_examples/2d_examples_ck/test_2d_water_entry_exit_ck/test_2d_water_entry_exit.cpp
  tests/tests_sycl/2d_examples/test_0d_regression_test_sycl/regression_test.cpp
  tests/tests_sycl/2d_examples/test_2d_diffusion_NeumannBC_sycl/CMakeLists.txt
  tests/tests_sycl/2d_examples/test_2d_diffusion_NeumannBC_sycl/diffusion_NeumannBC.cpp
  tests/tests_sycl/2d_examples/test_2d_diffusion_NeumannBC_sycl/regression_test_tool/TemperatureObserver_Phi_ensemble_averaged_mean_variance.xml
  tests/tests_sycl/2d_examples/test_2d_diffusion_NeumannBC_sycl/regression_test_tool/TemperatureObserver_Phi_result.xml
  tests/tests_sycl/2d_examples/test_2d_diffusion_NeumannBC_sycl/regression_test_tool/TemperatureObserver_Phi_runtimes.dat
  tests/tests_sycl/2d_examples/test_2d_diffusion_NeumannBC_sycl/regression_test_tool/regression_test_tool.py
Labels: sycl_ck

#739 Xiangyu/real ghost particles
  src/shared/bodies/complex_bodies/unstructured_mesh.cpp
  src/shared/body_relations/base_body_relation.cpp
  src/shared/io_system/io_base.cpp
  src/shared/io_system/io_base.h
  src/shared/particle_dynamics/base_local_dynamics.h
  src/shared/particles/base_particles.cpp
  src/shared/particles/base_particles.h
  src/shared/particles/base_particles.hpp
  src/shared/particles/particle_operation.cpp
  src/shared/particles/particle_operation.h
  src/shared/particles/particle_operation.hpp
  src/shared/particles/particle_reserve.cpp
  src/shared/shared_ck/body_relation/relation_ck.cpp
  src/shared/shared_ck/particle_dynamics/diffusion_reaction_dynamics/diffusion_dynamics_ck.hpp
Labels: sycl_ck

#758 Fix/register get variables
  src/shared/particles/base_particles.h
  src/shared/particles/base_particles.hpp
  src/shared/shared_ck/particle_dynamics/diffusion_reaction_dynamics/diffusion_dynamics_ck.h
  src/shared/shared_ck/particle_dynamics/diffusion_reaction_dynamics/diffusion_dynamics_ck.hpp
Labels: refactory

#762 Add missing kernel for Inner relation
  src/shared/shared_ck/particle_dynamics/interaction_algorithms_ck.hpp
Labels: bug, sycl_ck
