Repository Xiangyu-Hu/SPHinXsys, pull requests merged in 2025-04, with the labels that each got.

#778 add a function to reset the file path by update the quantity name, to…
  src/shared/io_system/io_observation.cpp
  src/shared/io_system/io_observation.h
  src/shared/shared_ck/io_system/io_observation_ck.h
  tests/extra_source_and_tests/test_2d_turbulent_channel/regression_test_tool/ObserverCenterPoint_TurbulentViscosity_dtwdistance.xml
Labels: bug

#794 using tabulated smoothing kernel to fit different analytical ones
  src/shared/shared_ck/neighborhood/neighborhood_ck.h
  src/shared/shared_ck/neighborhood/neighborhood_ck.hpp
  src/shared/shared_ck/smoothing_kernel/kernel_tabulated_ck.cpp
  src/shared/shared_ck/smoothing_kernel/kernel_tabulated_ck.h
Labels: sycl_ck

#795 Xiangyu/level set out inner package only
  .github/workflows/ci.yml
  src/for_2D_build/meshes/mesh_iterators.hpp
  src/for_2D_build/meshes/mesh_local_dynamics_2d.cpp
  src/for_3D_build/meshes/mesh_iterators.hpp
  src/for_3D_build/meshes/mesh_local_dynamics_3d.cpp
  src/for_3D_build/meshes/write_mesh_field_to_plt.cpp
  src/for_3D_build/meshes/write_mesh_field_to_plt.h
  src/shared/geometries/level_set.h
  src/shared/io_system/io_plt.cpp
  src/shared/io_system/io_plt.h
  src/shared/meshes/base_mesh.h
  src/shared/meshes/cell_linked_list.cpp
  src/shared/meshes/cell_linked_list.h
  src/shared/meshes/mesh_iterators.h
  src/shared/meshes/mesh_local_dynamics.h
  src/shared/meshes/mesh_with_data_packages.h
Labels: enhancement

#798 Xiangyu/second order derivative
  CMakeLists.txt
  src/for_2D_build/common/data_type.h
  src/for_3D_build/common/data_type.h
  src/shared/common/base_data_package.h
  src/shared/common/base_data_type.h
  src/shared/common/scalar_numerics.h
  src/shared/common/vector_functions.h
  src/shared/io_system/io_all.h
  src/shared/io_system/io_observation.h
  src/shared/io_system/io_plt.cpp
  src/shared/io_system/io_plt.h
  src/shared/io_system/io_plt.hpp
  src/shared/particle_dynamics/relax_dynamics/relax_stepping.h
  src/shared/shared_ck/particle_dynamics/general_dynamics/all_general_dynamics_ck.h
  src/shared/shared_ck/particle_dynamics/general_dynamics/general_gradient.h
  src/shared/shared_ck/particle_dynamics/general_dynamics/general_gradient.hpp
  src/shared/shared_ck/particle_dynamics/general_dynamics/hessian_correction_ck.h
  src/shared/shared_ck/particle_dynamics/general_dynamics/hessian_correction_ck.hpp
  src/shared/shared_ck/particle_dynamics/general_dynamics/interpolation_dynamics.h
  src/shared/tools/xml_parser.h
  tests/tests_sycl/unit_test_src/shared/particle_dynamics/general_dynamics/unit_test_gradient_sycl/2d_gradient.cpp
  tests/tests_sycl/unit_test_src/shared/particle_dynamics/general_dynamics/unit_test_gradient_sycl/CMakeLists.txt
  tests/unit_tests_src/shared/particle_dynamics/general_dynamics/unit_test_gradient_ck/2d_gradient.cpp
  tests/unit_tests_src/shared/particle_dynamics/general_dynamics/unit_test_gradient_ck/CMakeLists.txt
  tests/unit_tests_src/shared/particle_dynamics/general_dynamics/unit_test_interpolation_ck/2d_interpolation.cpp
Labels: sycl_ck

#803 sycl-ck/fix bidirectional boundary condition #802
  src/shared/shared_ck/particle_dynamics/fluid_dynamics/acoustic_step_2nd_half.h
  src/shared/shared_ck/particle_dynamics/fluid_dynamics/boundary_condition/bidirectional_boundary_ck.hpp
  tests/2d_examples/2d_examples_ck/test_2d_mixed_poiseuille_flow_ck/mixed_poiseuille_flow.cpp
  tests/3d_examples/3d_examples_ck/test_3d_mixed_poiseuille_flow_ck/mixed_poiseuille_flow.cpp
  tests/tests_sycl/2d_examples/test_2d_mixed_poiseuille_flow_sycl/mixed_poiseuille_flow.cpp
  tests/tests_sycl/3d_examples/test_3d_mixed_poiseuille_flow_sycl/mixed_poiseuille_flow.cpp
Labels: bug
